### ISSUE TITLE
Come help us out some?

### ISSUE THREAD

**Issue by SelfhostedPro** [Qballjos/portainer_templates#13]
Hey, is there any way you'd be willing to come help us keep up with issues here?
https://github.com/SelfhostedPro/selfhosted_templates

If not I totally understand I just wanted to reach out since we're getting a little overwhelmed with all the requests. If you want to talk our discord is here: https://discord.gg/d7np9fX

**Comment by Qballjos** [comment]
thanks for the nice chat let's keep in touch ;-)
