### ISSUE TITLE
[FEATURE REQUEST]: Support for Portainer v2

### ISSUE THREAD

**Issue by hirenshah** [Qballjos/portainer_templates#14]
The json format for Portainer v2 has changed:
https://github.com/portainer/templates/blob/master/templates-2.0.json

This [template.json](https://raw.githubusercontent.com/Qballjos/portainer_templates/master/Template/template.json) file results in an "unable to retrieve templates" error when loading the App Templates page.

**Comment by Qballjos** [comment]
I understand that portainer 2.0 will be out 1 of these days, and I'll look into creating a new template.

**Comment by xe-nvdk** [comment]
Hello there. I just converted your current template.json to be compatible with Portainer 2.0

**Comment by xe-nvdk** [comment]
https://github.com/Qballjos/portainer_templates/pull/15

**Comment by Qballjos** [comment]
The converted template has now been merged, so this issue is closed
