### ISSUE TITLE
Bookstack fails to install

### ISSUE THREAD

**Issue by mrcwatling** [Qballjos/portainer_templates#21]
Hi,
I have tried with v1 of the templates on v1.2.4 of portainer and then on V2 with 2.0.0 of portainer and the bookstack template always fails with the following errors in the log.

`Running config - db_user set
/var/run/s6/etc/cont-init.d/50-config: line 77: warning: command substitution: ignored null byte in input
/var/run/s6/etc/cont-init.d/50-config: line 77: warning: command substitution: ignored null byte in input
   Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'bookstack.bookstack_default' (using password: YES) (SQL: select * from information_schema.tables where table_schema = bookstackapp and table_name = migrations and table_type = 'BASE TABLE')
  at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|        catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|
  Exception trace:
  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'bookstack.bookstack_default' (using password: YES)")
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31
  2   PDOException::("SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'bookstack.bookstack_default' (using password: YES)")
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
  Please use the argument -v to see more details.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
`

The databse is created and is running but the bookstack docker can't login to the database.

Is there anyway to fix this?

**Comment by Qballjos** [comment]
it looks like the environmental settings aren't passed on, i'll have a look at it sorry for the late response

**Comment by Qballjos** [comment]
I think I found the issue the database create is called bookstackapp but it is trying to connect to bookstack
i'll try to fix it tomorrow.

**Comment by thunderwood19** [comment]
Issue still occuring. Manually setting up a separate database and connecting the bookstack container to that one allows the app to run.

**Comment by Qballjos** [comment]
I have just build this stack on my local macine and dont seem to have any issues....
![image](https://user-images.githubusercontent.com/1911646/107147646-66070100-694f-11eb-8daa-6cbe47f4e89c.png)

The database is created and tables are build
![Screenshot 2021-02-07 at 14 26 39](https://user-images.githubusercontent.com/1911646/107147858-93a07a00-6950-11eb-8abe-dd2f40cc3fdc.png)

After setting the app url in enviromental settings im also able to login and create books.
![image](https://user-images.githubusercontent.com/1911646/107148245-7e2c4f80-6952-11eb-9e37-4e2f08f6c0c3.png)

**Comment by Qballjos** [comment]
At this moment I must conclude that the stack is good, im unable te recreate the errors you are getting.

Sorry for the delay in responding I was/am batteling after effects of covid-19
