### ISSUE TITLE
Clarify the overlap/difference between this repo and portainer

### ISSUE THREAD

**Issue by Kipjr** [Qballjos/portainer_templates#23]
Hi, 
Portainer also publishes portainer templates. How does this repo differs from that one? Are some packages omitted or do both template packages have no overlap? 

Can this be mentioned in README.md and the Github.io page?

**Comment by Qballjos** [comment]
This template was created because portainer stopped hosting the images/template of linuxserver.io.
If you want know what images and templates are provided here you can find it in the readme.
As of what portainer is hosting is not something i'm going to monitor or add to my personal template.
