### ISSUE TITLE
[BUG] Backup listed twice

### ISSUE THREAD

**Issue by DrSeussFreak** [Qballjos/portainer_templates#24]
**Describe the bug**
Simple category bug, you have "Backup" and "Backup:"

**To Reproduce**
1) Go to app catalogs
2) Select the dropdown for categories

**Expected behavior**
The 3 backup apps to be in 1 category

**Screenshots**
![Screen Shot 2021-03-19 at 11 48 20 AM](https://user-images.githubusercontent.com/175500/111814891-02a2b400-88a9-11eb-8959-42b5e38137d0.png)

**Portainer Logs**
n/a

**Comment by Qballjos** [comment]
Thnx for the issue report fixed it for you

**Comment by DrSeussFreak** [comment]
Thank-you!
