### ISSUE TITLE
'category' field should be 'categories'

### ISSUE THREAD

**Issue by softrockstar** [Qballjos/portainer_templates#3]
Thanks for this. Apart from alphabetizing the list, it might be useful to replace the 'category' field with 'categories' [per the portainer docs](https://portainer.readthedocs.io/en/stable/templates.html#categories). I think this is why portainer's tempate page doesn't currently populate the drop-down menu with any categories.

**Comment by Qballjos** [comment]
thnx for the update i have updated it per request
