### ISSUE TITLE
Duplicati and syncthing not working

### ISSUE THREAD

**Issue by japatel5213** [Qballjos/portainer_templates#32]
Duplicati and Syncthing deploy successfully but not connect the browser. means...
![image](https://user-images.githubusercontent.com/24197070/119991948-a4e8c180-bfe7-11eb-9fd3-9e86d51eaf6f.png)
Any Configuration at Deploying?

**Comment by Qballjos** [comment]
I'm unable to help with this little info please provide more... like the deployment configs, logs etc.
