### ISSUE TITLE
Images missing

### ISSUE THREAD

**Issue by keppo070** [Qballjos/portainer_templates#4]
Just tried your template. It seems to be missing some images.

I like this template. Most of my dockers are from linuxserver.io. What I dislike is that Portainer disables the internal templates when used with  an external template. I was hoping to get them both.

The template still works with Portainer 1.23.2

**Comment by peylight** [comment]
You should merge this templates with the [official templates](https://github.com/portainer/templates)
@OBenned 
Why you don't do it?

**Comment by OBenned** [comment]
@peylight What do you mean, i have nothing to do with this?

**Comment by peylight** [comment]
@OBenned 
Actually be better to add more portainer templates (not just change). So it is about portainer ability.
I make an issue for this in portainer github page:
https://github.com/portainer/portainer/issues/3845

**Comment by OBenned** [comment]
Sure, but still im not the owner of this repo

**Comment by Qballjos** [comment]
This repo has been made on a copy of the previously automatically generated template from linuxserver.io.
This now has to be manually edited there fore it's not suitable to be added to the portainer repo witch it previously was.
If things are missing or need to bee changed please make a pull request or send me the details to be fixed.
This is all is being done on a volunteer basis by me and other that help.

**Comment by Qballjos** [comment]
@keppo070 Are you able to make a pull request with the images you want to add, or provide me with a list you wish to be added i'll have a look at it.

**Comment by keppo070** [comment]
i dont speak github, but I made an effort to do so. Not sure, if everything is ok like this. I will add more if I run into some. Not exactly know why I should make a fork to make a pull...but I will google it.

**Comment by Qballjos** [comment]
Oke thanks you!
