### ISSUE TITLE
[APP REQUEST]:  Uptime Kuma

### ISSUE THREAD

**Issue by beardsleym** [Qballjos/portainer_templates#48]
### Dockerhub Link: ###
https://hub.docker.com/r/louislam/uptime-kuma

### Description ###
It is a self-hosted monitoring tool like "Uptime Robot".

### Separate Database? ###
No

### Fill this out as best as you can. Documentation about these can be found here: https://www.portainer.io/documentation/how-to-use-templates/

[mycroftwilde template example](https://raw.githubusercontent.com/mycroftwilde/portainer_templates/master/Template/template.json)

```json
{
      "categories": [
        "Task Server"
      ],
      "description": "It is a self-hosted monitoring tool like Uptime Robot",
      "image": "louislam/uptime-kuma:latest",
      "logo": "https://images.opencollective.com/uptime-kuma/29c5113/logo/256.png",
      "name": "uptime-kuma",
      "platform": "linux",
      "ports": [
        "3001:3001/tcp"
      ],
      "restart_policy": "always",
      "title": "Uptime Kuma",
      "type": 1,
      "volumes": [
        {
          "bind": "/portainer/Files/AppData/Config/UptimeKuma",
          "container": "/app/data"
        }
      ]
    },
```

**Comment by Qballjos** [comment]
thnx for your input sorry for the late response, i'll have a look at it tonight

**Comment by 0lzi** [comment]
confirmed the above works provided by @beardsleym , I would make a PR but I changed all the image directories to my fork

**Comment by Qballjos** [comment]
uptime kuma has been added, sorry for the delay
