### ISSUE TITLE
Overseerr issue

### ISSUE THREAD

**Issue by IanAlbinson** [Qballjos/portainer_templates#58]
Thanks for this resource!

I attempted to install Overseerr today but am receiving this error: No such image: hotio/overseerr:release

Do you know of any way around this?

**Comment by Qballjos** [comment]
I checked it seems the changed the label to latest fixed this now

**Comment by IanAlbinson** [comment]
Do I need to refresh your templates in any way? Still receiving that same error when I try to deploy.
