### ISSUE TITLE
Overseerr issue again

### ISSUE THREAD

**Issue by IanAlbinson** [Qballjos/portainer_templates#59]
You'd closed a previous issue but I wasn't able to make it work.

Do I need to refresh your templates in any way? Still receiving that same error when I try to deploy.

I get a "Failure No such image: hotio/overseerr:latest" error.

Thank you!

**Comment by wickedyoda** [comment]
The repo hasn't been maintained in 3+ years, your not going to find support here.

**Comment by Qballjos** [comment]
updated template to use release (this is the latest tage for this repo)
