### ISSUE TITLE
[BUG] Missing ports mapping for Deluge template

### ISSUE THREAD

**Issue by onikienko** [Qballjos/portainer_templates#62]
**Describe the bug**
Missing ports mapping for Deluge template.

**To Reproduce**
Open Deluge template in portainer

**Expected behavior**
Put default port binding.
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp

**Screenshots**
![image](https://user-images.githubusercontent.com/3234928/220167353-e72155cd-0d78-4716-a99a-4628d619f0bf.png)

**Comment by wickedyoda** [comment]
The repo hasn't been maintained in 3+ years, your not going to find support here.

**Comment by Qballjos** [comment]
added the ports to teh template
