### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by randompea** [Qballjos/portainer_templates#64]
**Describe the bug**
Vaultwarden will not install, gives error
**To Reproduce**
1. Go to templates
2. Click on vaultwarden
3. Scroll down to install
4. See error in logs "# This will result in permanent data loss when the container is removed or updated!    #
# If you really want to use volatile storage set `I_REALLY_WANT_VOLATILE_STORAGE=true` #
# It looks like you did not configure a persistent volume!                             #
########################################################################################
[2023-04-09 16:35:14.906][vaultwarden][ERROR] No persistent volume!"

**Expected behavior**
vaultwarden to boot
**Screenshots**

**Portainer Logs**
# This will result in permanent data loss when the container is removed or updated!    #
# If you really want to use volatile storage set `I_REALLY_WANT_VOLATILE_STORAGE=true` #
# It looks like you did not configure a persistent volume!                             #
########################################################################################
[2023-04-09 16:35:14.906][vaultwarden][ERROR] No persistent volume!

**Comment by wickedyoda** [comment]
The repo hasn't been maintained in 3+ years, your not going to find support here.

**Comment by Qballjos** [comment]
updated the template to use the /data folder this should fix the persistant data issue -> https://github.com/dani-garcia/vaultwarden/issues/2622
